version: '3'

services:
  api:
    container_name: api
    image: blockaction-api
    environment:
      - PORT=8081
    ports:
      - 8081:8081
    volumes:
      - "./conf.d:/app/conf.d"
    restart: always
    depends_on:
      mysql:
        condition: service_healthy
  mysql:
    container_name: mysql
    image: mysql:8.1
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: '!QAZ2wsx'
      MYSQL_DATABASE: 'blockaction'
    ports:
      - 3306:3306
    volumes:
      - "./init.sql:/docker-entrypoint-initdb.d/1.sql"
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      interval: 1s
      timeout: 3s
      retries: 20
    